site_name: TEQSAS PRODUCTS Documentation
site_url: https://docs.teqsas.de/

extra_css:
  - stylesheets/extra.css



theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - navigation.top

  icon:
    admonition:
      info: octicons/info-16
      danger: octicons/alert-16
      warning: octicons/alert-16
      abstract: octicons/alert-16

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  palette:
    scheme: slate
    primary: black
    accent: orange




nav:
  - Home: index.md
  - Products:
    - 'PAN-C': 
      - PANC/index.md
      - Bevor Sie beginnen: PANC/Manual/manual_1.md
      - Zu Ihrer Sicherheit: PANC/Manual/manual_2.md
      - Produktbeschreibung: PANC/Manual/manual_3.md
      - Inbetriebnahme: PANC/Manual/manual_4.md
      - Bedienung: PANC/Manual/manual_5.md
    - 'LAP-TEQ PLUS INTERFACE': 
      - INTERFACE/API/INTERFACE_API.md
      # - INTERFACE/FAQ/INTERFACE_FAQ.md
  - Support: support/support.md

  # - Contact: contact.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  

