site_name: TEQSAS Products Documentation
site_url: https://docs.teqsas.de
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: orange

plugins:
  
  
copyright: |
  &copy; 2023 <a href="https://github.com/teqsas"  target="_blank" rel="noopener">TEQSAS GmbH</a>