site_name: TEQSAS PRODUCTS
site_url: https://docs.teqsas.de/

extra_css:
  - stylesheets/extra.css

extra:
  alternate:
    - name: Deutsch
      link: /
      lang: de
    - name: English
      link: /en/
      lang: en

theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.tabs.link

  icon:
    admonition:
      info: octicons/info-16
      danger: octicons/alert-16
      warning: octicons/alert-16
      abstract: octicons/alert-16

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  palette:
    scheme: slate
    primary: black
    accent: orange

nav:
  - Startseite: index.md
  - Produkte:
    - 'PAN-C':
      - PANC/index.md
      - Bedienungsanleitung:
        - Einstieg:
          - Bevor Sie beginnen: PANC/Manual/manual_1.md
          - Zu Ihrer Sicherheit: PANC/Manual/manual_2.md
          - Produktbeschreibung: PANC/Manual/manual_3.md
        - Betrieb:
          - Inbetriebnahme: PANC/Manual/manual_4.md
          - Bedienung: PANC/Manual/manual_5.md
          - Reinigung und Pflege: PANC/Manual/manual_6.md
        - Service:
          - Störungen und Hilfe: PANC/Manual/manual_7.md
        - Referenz:
          - CE-Konformitätserklärung: PANC/Manual/manual_ce.md
    - 'LAP-TEQ PLUS':
      - LAPTEQPLUS/index.md
      - Bedienungsanleitung:
        - Einstieg:
          - Bevor Sie beginnen: LAPTEQPLUS/Manual/manual_1.md
          - Zu Ihrer Sicherheit: LAPTEQPLUS/Manual/manual_2.md
          - Produktbeschreibung: LAPTEQPLUS/Manual/manual_3.md
        - Betrieb:
          - Inbetriebnahme: LAPTEQPLUS/Manual/manual_4.md
          - Bedienung: LAPTEQPLUS/Manual/manual_5.md
          - Reinigung und Pflege: LAPTEQPLUS/Manual/manual_6.md
        - Service:
          - Störungen und Hilfe: LAPTEQPLUS/Manual/manual_7.md
          - Kalibrierung: LAPTEQPLUS/Manual/manual_8.md
          - Lagerung: LAPTEQPLUS/Manual/manual_9.md
          - Entsorgung: LAPTEQPLUS/Manual/manual_10.md
        - Referenz:
          - Technische Daten: LAPTEQPLUS/Manual/manual_11.md
          - CE-Konformitätserklärung: LAPTEQPLUS/Manual/manual_ce.md
    - 'LAP-TEQ PLUS INTERFACE':
      - INTERFACE/index.md
      - Bedienungsanleitung:
        - Einstieg:
          - Bevor Sie beginnen: INTERFACE/Manual/manual_1.md
          - Zu Ihrer Sicherheit: INTERFACE/Manual/manual_2.md
          - Produktbeschreibung: INTERFACE/Manual/manual_3.md
        - Betrieb:
          - Inbetriebnahme: INTERFACE/Manual/manual_4.md
          - Bedienung: INTERFACE/Manual/manual_5.md
          - Reinigung und Pflege: INTERFACE/Manual/manual_6.md
        - Service:
          - Störungen und Hilfe: INTERFACE/Manual/manual_7.md
          - Entsorgung: INTERFACE/Manual/manual_10.md
        - Referenz:
          - Technische Daten: INTERFACE/Manual/manual_11.md
          - CE-Konformitätserklärung: INTERFACE/Manual/manual_ce.md
      - API: INTERFACE/API/INTERFACE_API.md
  - Support: support/support.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: de
          default: true
          name: Deutsch
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Startseite: Home
            Produkte: Products
            Bedienungsanleitung: Manual
            Einstieg: Getting started
            Betrieb: Operation
            Service: Service
            Referenz: Reference
            Bevor Sie beginnen: Before you begin
            Zu Ihrer Sicherheit: For your safety
            Produktbeschreibung:  Product Description
            Inbetriebnahme: Powering up
            Bedienung:  Usage
            Reinigung und Pflege: Cleaning
            Störungen und Hilfe:  Issues and Help
            Kalibrierung: Calibration
            Lagerung: Storage
            Entsorgung: Disposal
            Technische Daten: Technical Data
            CE-Konformitätserklärung: Regulations
