site_name: TEQSAS PRODUCTS Documentation
site_url: https://docs.teqsas.de/

extra_css:
  - stylesheets/extra.css



theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - navigation.top

  icon:
    admonition:
      info: octicons/info-16
      danger: octicons/alert-16
      warning: octicons/alert-16
      abstract: octicons/alert-16

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  palette:
    scheme: slate
    primary: black
    accent: orange




nav:
  - Home: index.md
  - Products:
    - 'PAN-C':
      - PANC/index.md
      - Bedienungsanleitung:
        - Bevor Sie beginnen: PANC/Manual/manual_1.md
        - Zu Ihrer Sicherheit: PANC/Manual/manual_2.md
        - Produktbeschreibung: PANC/Manual/manual_3.md
        - Inbetriebnahme: PANC/Manual/manual_4.md
        - Bedienung: PANC/Manual/manual_5.md
        - Reinigung und Pflege: PANC/Manual/manual_6.md
        - Störungen und Hilfe: PANC/Manual/manual_7.md
        - CE-Konformitätserklärung: PANC/Manual/manual_ce.md
    - 'LAP-TEQ PLUS INTERFACE': 
      - INTERFACE/API/INTERFACE_API.md
      # - INTERFACE/FAQ/INTERFACE_FAQ.md
  - Support: support/support.md

  # - Contact: contact.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: de
          default: true
          name: Deutsch
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Bedienungsanleitung: Manual
            Bevor Sie beginnen: Before you begin
            Zu Ihrer Sicherheit: For your safety
            Produktbeschreibung:  Product Description
            Inbetriebnahme: Powering up
            Bedienung:  Usage
            Reinigung und Pflege: Cleaning
            Störungen und Hilfe:  Issues and Help
            CE-Konformitätserklärung: Regulations