site_name: TEQSAS PRODUCTS Documentation
site_url: https://docs.teqsas.de/

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.png
  features:

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  palette:
    scheme: slate
    primary: black
    accent: orange




  
copyright: |
  &copy; 2023 <a href="https://teqsas.de"  target="_blank" rel="noopener">TEQSAS GmbH</a>
