site_name: TEQSAS PRODUCTS Documentation
site_url: https://docs.teqsas.de/

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/logo.png
  features:

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

  palette:
      # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: custom
 
      # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: custom




  
copyright: |
  &copy; 2023 <a href="https://github.com/teqsas"  target="_blank" rel="noopener">TEQSAS GmbH</a>